-- MySQL Script generated by MySQL Workbench
-- Wed May 13 20:03:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema comma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comma` DEFAULT CHARACTER SET euckr ;
USE `comma` ;

-- -----------------------------------------------------
-- Table `comma`.`tbl_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_song` (
  `s_id` INT(11) NOT NULL,
  `s_title` VARCHAR(100) NOT NULL,
  `s_artist` VARCHAR(30) NOT NULL,
  `s_file` VARCHAR(60) NOT NULL,
  `s_url` TEXT NULL DEFAULT NULL,
  `s_description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`s_id`),
  UNIQUE INDEX `t_id_UNIQUE` (`s_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr
COMMENT = '		';


-- -----------------------------------------------------
-- Table `comma`.`tbl_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_album` (
  `a_id` INT(11) NOT NULL AUTO_INCREMENT,
  `a_title` VARCHAR(100) NOT NULL,
  `s_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`a_id`),
  INDEX `FK_tbl_album_tbl_song` (`s_id` ASC) VISIBLE,
  CONSTRAINT `FK_tbl_album_tbl_song`
    FOREIGN KEY (`s_id`)
    REFERENCES `comma`.`tbl_song` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `comma`.`tbl_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_member` (
  `m_id` VARCHAR(30) NOT NULL,
  `m_pwd` VARCHAR(30) NOT NULL,
  `m_name` VARCHAR(30) NULL DEFAULT NULL,
  `m_email` VARCHAR(30) NOT NULL,
  `m_birth` DATE NULL DEFAULT NULL,
  `m_visited` DATE NULL DEFAULT NULL,
  `m_auth` ENUM('artist', 'admin') NULL DEFAULT 'artist',
  PRIMARY KEY (`m_id`),
  UNIQUE INDEX `id_UNIQUE` (`m_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`m_email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`m_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `comma`.`tbl_heart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_heart` (
  `h_id` INT(11) NOT NULL AUTO_INCREMENT,
  `m_id` VARCHAR(30) NULL DEFAULT NULL,
  `s_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`h_id`),
  INDEX `FK_tbl_heart_tbl_member` (`m_id` ASC) VISIBLE,
  INDEX `FK_tbl_heart_tbl_song` (`s_id` ASC) VISIBLE,
  CONSTRAINT `FK_tbl_heart_tbl_member`
    FOREIGN KEY (`m_id`)
    REFERENCES `comma`.`tbl_member` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_tbl_heart_tbl_song`
    FOREIGN KEY (`s_id`)
    REFERENCES `comma`.`tbl_song` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `comma`.`tbl_play_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_play_log` (
  `m_id` VARCHAR(30) NULL DEFAULT NULL,
  `p_id` INT(11) NOT NULL AUTO_INCREMENT,
  `p_count` INT(11) NULL DEFAULT '0',
  `p_last` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`p_id`),
  INDEX `FK_tbl_play_log_tbl_member` (`m_id` ASC) VISIBLE,
  CONSTRAINT `FK_tbl_play_log_tbl_member`
    FOREIGN KEY (`m_id`)
    REFERENCES `comma`.`tbl_member` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
