-- MySQL Script generated by MySQL Workbench
-- Thu May 14 18:40:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema comma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comma` DEFAULT CHARACTER SET euckr ;
USE `comma` ;

-- -----------------------------------------------------
-- Table `comma`.`tbl_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_member` (
  `m_id` VARCHAR(30) NOT NULL COMMENT 'member id',
  `m_pwd` VARCHAR(100) NOT NULL COMMENT 'member password',
  `m_email` VARCHAR(30) NOT NULL COMMENT 'member email',
  `m_birth` DATE NULL DEFAULT NULL COMMENT 'member birthday',
  `m_visited` DATE NULL DEFAULT NULL COMMENT 'member last login date, visited',
  `m_auth` ENUM('admin', 'user') NULL DEFAULT 'user' COMMENT 'member auth(admin, user)',
  PRIMARY KEY (`m_id`),
  UNIQUE INDEX `email_UNIQUE` (`m_email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `comma`.`tbl_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_song` (
  `s_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'song id',
  `s_title` VARCHAR(200) NOT NULL COMMENT 'song title',
  `m_id` VARCHAR(30) NOT NULL COMMENT 'member id',
  `s_artist` VARCHAR(100) NOT NULL COMMENT 'member_id',
  `s_file` TEXT NOT NULL COMMENT 'song file path',
  `s_url` TEXT NULL DEFAULT NULL COMMENT 'song web url link',
  `s_lyrics` TEXT NULL DEFAULT NULL COMMENT 'song lyrics',
  `s_age` INT(10) UNSIGNED NULL DEFAULT '0' COMMENT 'song min age required',
  PRIMARY KEY (`s_id`),
  INDEX `FK_tbl_song_tbl_member` (`m_id` ASC) VISIBLE,
  CONSTRAINT `FK_tbl_song_tbl_member`
    FOREIGN KEY (`m_id`)
    REFERENCES `comma`.`tbl_member` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `comma`.`tbl_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_comment` (
  `c_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'comment id',
  `m_id` VARCHAR(30) NULL DEFAULT NULL COMMENT 'member id',
  `c_content` TEXT NULL DEFAULT NULL COMMENT 'comment content',
  `s_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`c_id`),
  INDEX `FK_tbl_comment_tbl_song` (`s_id` ASC) VISIBLE,
  INDEX `FK_tbl_comment_tbl_member` (`m_id` ASC) VISIBLE,
  CONSTRAINT `FK_tbl_comment_tbl_member`
    FOREIGN KEY (`m_id`)
    REFERENCES `comma`.`tbl_member` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_tbl_comment_tbl_song`
    FOREIGN KEY (`s_id`)
    REFERENCES `comma`.`tbl_song` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `comma`.`tbl_heart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_heart` (
  `h_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'heart (like) id',
  `m_id` VARCHAR(30) NULL DEFAULT NULL COMMENT 'member id',
  `s_id` INT(11) NULL DEFAULT NULL COMMENT 'song id',
  PRIMARY KEY (`h_id`),
  UNIQUE INDEX `m_id_s_id` (`m_id` ASC, `s_id` ASC) VISIBLE,
  INDEX `FK_tbl_heart_tbl_song` (`s_id` ASC) VISIBLE,
  CONSTRAINT `FK_tbl_heart_tbl_member`
    FOREIGN KEY (`m_id`)
    REFERENCES `comma`.`tbl_member` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_tbl_heart_tbl_song`
    FOREIGN KEY (`s_id`)
    REFERENCES `comma`.`tbl_song` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `comma`.`tbl_playlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_playlog` (
  `p_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'playlist id',
  `m_id` VARCHAR(30) NULL DEFAULT NULL COMMENT 'member id',
  `s_id` INT(11) NULL DEFAULT NULL COMMENT 'song id',
  `p_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'playlist time',
  PRIMARY KEY USING BTREE (`p_id`),
  INDEX `FK_tbl_play_log_tbl_member` USING BTREE (`m_id`) VISIBLE,
  INDEX `FK_tbl_play_log_tbl_song` USING BTREE (`s_id`) VISIBLE,
  CONSTRAINT `FK_tbl_playlog_tbl_member`
    FOREIGN KEY (`m_id`)
    REFERENCES `comma`.`tbl_member` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_tbl_playlog_tbl_song`
    FOREIGN KEY (`s_id`)
    REFERENCES `comma`.`tbl_song` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `comma`.`tbl_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comma`.`tbl_tag` (
  `t_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'tag id',
  `t_name` VARCHAR(45) NOT NULL COMMENT 'tag name',
  `s_id` INT(11) NULL DEFAULT NULL COMMENT 'song id',
  `m_id` VARCHAR(30) NULL DEFAULT NULL COMMENT 'member id',
  PRIMARY KEY USING BTREE (`t_id`),
  INDEX `FK1` (`s_id` ASC) VISIBLE,
  INDEX `FK_tbl_tag_tbl_member` (`m_id` ASC) VISIBLE,
  CONSTRAINT `FK_tbl_tag_tbl_member`
    FOREIGN KEY (`m_id`)
    REFERENCES `comma`.`tbl_member` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_tbl_tag_tbl_song`
    FOREIGN KEY (`s_id`)
    REFERENCES `comma`.`tbl_song` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
